from django.urls import path

from .views import (
    HealthCheck,
    LoginView,
    MeView,
    RegisterView,
    LogoutView,
    ConfigView,
    ProjectRegisterView,
    AgentJobRequestView,
    AgentJobStartView,
    AgentJobProgressView,
    AgentJobCompleteView,
    AgentToolCallbackView,
    AgentTelemetryView,
    AgentHeartbeatView,
    ProjectScanView,
    ProjectIssuesView,
    ProjectReadmeView,
    ProjectCommitsView,
    CreateAgentJobView,
    JobDetailView,
    ProjectListView,
    DeviceLoginView,
    DeviceUpdatesView,
    TasksAssignedView,
    UploadsView,
    ActivityLogsView,
    MobileLoginView,
    MobileFeedView,
    MobileFeedbackView,
    NotificationsView,
    NotificationsTokenView,
    QuizPoolsView,
    QuizSessionsView,
    QuizSessionDetailView,
    QuizSessionAnswersView,
    QuizSessionFinishView,
    QuizHistoryView,
    QuizRecommendationsView,
    QuizGeneratedSaveView,
)

# Use real gamification endpoints from the gamification app
from gamification.views import (
    ProfileAPIView as GamiProfileView,
    EventAPIView as GamiEventsView,
    BadgeAPIView as GamiBadgesView,
    RedeemAPIView as GamiRedeemView,
    LeaderboardAPIView as GamiLeaderboardView,
)

urlpatterns = [
    path('health', HealthCheck.as_view(), name='health_check'),
    path('me', MeView.as_view(), name='me'),
    path('auth/register', RegisterView.as_view(), name='register'),
    path('auth/logout', LogoutView.as_view(), name='logout'),
    path('config', ConfigView.as_view(), name='config'),
    path('git/projects/register', ProjectRegisterView.as_view(), name='project_register'),
    path('agent/jobs/request', AgentJobRequestView.as_view(), name='agent_job_request'),
    path('agent/jobs/<int:job_id>/start', AgentJobStartView.as_view(), name='agent_job_start'),
    path('agent/jobs/<int:job_id>/progress', AgentJobProgressView.as_view(), name='agent_job_progress'),
    path('agent/jobs/<int:job_id>/complete', AgentJobCompleteView.as_view(), name='agent_job_complete'),
    path('agent/callbacks/tool', AgentToolCallbackView.as_view(), name='agent_tool_callback'),
    path('agent/telemetry', AgentTelemetryView.as_view(), name='agent_telemetry'),
    path('agent/heartbeat', AgentHeartbeatView.as_view(), name='agent_heartbeat'),
    path('git/<int:project_id>/scan', ProjectScanView.as_view(), name='project_scan'),
    path('git/<int:project_id>/issues', ProjectIssuesView.as_view(), name='project_issues'),
    path('git/<int:project_id>/readme', ProjectReadmeView.as_view(), name='project_readme'),
    path('git/<int:project_id>/commits', ProjectCommitsView.as_view(), name='project_commits'),
    path('projects/<int:project_id>/jobs', CreateAgentJobView.as_view(), name='create_agent_job'),
    path('projects/<int:project_id>/jobs/<int:job_id>', JobDetailView.as_view(), name='job_detail'),
    path('projects', ProjectListView.as_view(), name='project_list'),
    path('device/login', DeviceLoginView.as_view(), name='device_login'),
    path('device/updates', DeviceUpdatesView.as_view(), name='device_updates'),
    path('tasks/assigned', TasksAssignedView.as_view(), name='tasks_assigned'),
    path('uploads', UploadsView.as_view(), name='uploads'),
    path('activity/logs', ActivityLogsView.as_view(), name='activity_logs'),
    path('auth/mobile/login', MobileLoginView.as_view(), name='mobile_login'),
    path('mobile/feed', MobileFeedView.as_view(), name='mobile_feed'),
    path('mobile/feedback', MobileFeedbackView.as_view(), name='mobile_feedback'),
    path('notifications', NotificationsView.as_view(), name='notifications'),
    path('notifications/token', NotificationsTokenView.as_view(), name='notifications_token'),
    # Quiz Engine
    path('quiz/pools', QuizPoolsView.as_view(), name='quiz_pools'),
    path('quiz/sessions', QuizSessionsView.as_view(), name='quiz_sessions'),
    path('quiz/sessions/<int:session_id>', QuizSessionDetailView.as_view(), name='quiz_session_detail'),
    path('quiz/sessions/<int:session_id>/answers', QuizSessionAnswersView.as_view(), name='quiz_session_answers'),
    path('quiz/sessions/<int:session_id>/finish', QuizSessionFinishView.as_view(), name='quiz_session_finish'),
    path('quiz/history', QuizHistoryView.as_view(), name='quiz_history'),
    path('quiz/recommendations', QuizRecommendationsView.as_view(), name='quiz_recommendations'),
    path('quiz/generated', QuizGeneratedSaveView.as_view(), name='quiz_generated_save'),
    # Gamification Engine
    path('gami/profile', GamiProfileView.as_view(), name='gami_profile'),
    path('gami/events', GamiEventsView.as_view(), name='gami_events'),
    path('gami/badges', GamiBadgesView.as_view(), name='gami_badges'),
    path('gami/redeem', GamiRedeemView.as_view(), name='gami_redeem'),
    path('gami/leaderboard', GamiLeaderboardView.as_view(), name='gami_leaderboard'),
]
