# Generated by Django 5.2.7 on 2025-11-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(related_name='sessions', to='quiz.question'),
        ),
    ]
