# Generated by Django 4.2.7 on 2025-11-01 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(help_text='배지 획득 조건')),
                ('icon', models.CharField(default='🏆', help_text='이모지 아이콘', max_length=10)),
                ('xp_reward', models.IntegerField(default=0, help_text='획득시 지급 XP')),
                ('points_reward', models.IntegerField(default=0, help_text='획득시 지급 포인트')),
                ('rarity', models.CharField(choices=[('common', '일반'), ('rare', '레어'), ('epic', '에픽'), ('legendary', '전설')], default='common', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '배지',
                'verbose_name_plural': '배지',
                'db_table': 'gami_badge',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='이벤트 이름', max_length=100, unique=True)),
                ('code', models.CharField(help_text='이벤트 코드 (예: QUIZ_COMPLETE)', max_length=50, unique=True)),
                ('xp_reward', models.IntegerField(default=0, help_text='지급 경험치')),
                ('points_reward', models.IntegerField(default=0, help_text='지급 포인트')),
                ('description', models.TextField(blank=True, help_text='이벤트 설명')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '이벤트 타입',
                'verbose_name_plural': '이벤트 타입',
                'db_table': 'gami_event_type',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🎁', max_length=10)),
                ('points_cost', models.IntegerField(help_text='필요 포인트')),
                ('reward_type', models.CharField(choices=[('coupon', '쿠폰'), ('role', '역할'), ('item', '아이템')], default='coupon', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='리워드 세부 정보')),
                ('stock', models.IntegerField(default=-1, help_text='재고 (-1: 무제한)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '리워드',
                'verbose_name_plural': '리워드',
                'db_table': 'gami_reward',
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('approved', '승인됨'), ('completed', '완료됨'), ('cancelled', '취소됨')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gami_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 리워드',
                'verbose_name_plural': '사용자 리워드',
                'db_table': 'gami_user_reward',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, help_text='누적 포인트')),
                ('level', models.IntegerField(default=1, help_text='현재 레벨')),
                ('xp', models.IntegerField(default=0, help_text='현재 경험치')),
                ('xp_to_next_level', models.IntegerField(default=100, help_text='다음 레벨까지 필요한 XP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gami_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
                'db_table': 'gami_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='추가 정보')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.eventtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gami_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 이벤트',
                'verbose_name_plural': '사용자 이벤트',
                'db_table': 'gami_user_event',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gami_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 배지',
                'verbose_name_plural': '사용자 배지',
                'db_table': 'gami_user_badge',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', '일일'), ('weekly', '주간'), ('monthly', '월간'), ('all_time', '전체')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('rank', models.IntegerField()),
                ('score', models.IntegerField(help_text='해당 기간 획득 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gami_leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '리더보드',
                'verbose_name_plural': '리더보드',
                'db_table': 'gami_leaderboard',
                'ordering': ['period_type', 'rank'],
                'indexes': [models.Index(fields=['period_type', 'period_start', 'period_end'], name='gami_leader_period__7309d6_idx')],
            },
        ),
    ]
