# Generated by Django 4.2.7 on 2025-11-01 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='퀘스트 제목', max_length=200)),
                ('description', models.TextField(help_text='퀘스트 설명')),
                ('quest_type', models.CharField(choices=[('daily_login', '일일 출석'), ('ai_generated', 'AI 생성')], default='ai_generated', max_length=50)),
                ('xp_reward', models.IntegerField(default=50, help_text='보상 경험치')),
                ('points_reward', models.IntegerField(default=10, help_text='보상 포인트')),
                ('date', models.DateField(help_text='퀘스트 날짜')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gami_daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일일 퀘스트',
                'verbose_name_plural': '일일 퀘스트',
                'db_table': 'gami_daily_quest',
                'ordering': ['-date', 'is_completed'],
                'indexes': [models.Index(fields=['user', 'date'], name='gami_daily__user_id_b11920_idx')],
                'unique_together': {('user', 'date', 'quest_type')},
            },
        ),
    ]
