# Generated by Django 4.2.7 on 2025-11-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_dailyquest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='xp_to_next_level',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0, help_text='누적 경험치'),
        ),
    ]
