# Generated by Django 4.2.7 on 2025-11-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_remove_userprofile_xp_to_next_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(choices=[('level', '레벨 도달'), ('total_xp', '누적 XP'), ('total_points', '누적 포인트'), ('quest_complete', '특정 퀘스트 완료'), ('quest_count', '퀘스트 완료 횟수'), ('event_count', '특정 이벤트 횟수'), ('manual', '수동 지급')], default='manual', help_text='배지 획득 조건 유형', max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='condition_value',
            field=models.CharField(blank=True, help_text='조건 값 (예: 레벨 5, 퀘스트코드, 횟수 등)', max_length=100, null=True),
        ),
    ]
