# Generated by Django 5.2.7 on 2025-11-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0004_badge_condition_type_badge_condition_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquest",
            name="points_reward",
            field=models.IntegerField(default=3, help_text="보상 포인트 (최대 5)"),
        ),
        migrations.AlterField(
            model_name="dailyquest",
            name="xp_reward",
            field=models.IntegerField(default=30, help_text="보상 경험치 (최대 50)"),
        ),
    ]
