# Generated by Django 5.2.7 on 2025-11-03 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_avg_complexity_project_file_tree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzer', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=1024)),
                ('line', models.IntegerField()),
                ('rule_id', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
