# Generated by Django 5.2.7 on 2025-11-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readme_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
