from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class QuizProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='quiz_profile')
    total_points = models.IntegerField(default=0)
    level = models.IntegerField(default=1)
    streak_days = models.IntegerField(default=0)
    last_quiz_date = models.DateField(null=True, blank=True)
    consecutive_correct = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user.username}'s Quiz Profile"

class Topic(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Difficulty(models.Model):
    name = models.CharField(max_length=50, unique=True) # e.g., beginner, intermediate, advanced
    level = models.IntegerField(unique=True) # e.g., 1, 2, 3

    def __str__(self):
        return self.name

class Question(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='questions')
    difficulty = models.ForeignKey(Difficulty, on_delete=models.CASCADE, related_name='questions')
    question_text = models.TextField()
    options = models.JSONField() # {"a": "Option 1", "b": "Option 2", ...}
    correct_answer = models.CharField(max_length=10) # "a", "b", ...
    explanation = models.TextField()
    learning_tip = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"[{self.difficulty.name}] {self.topic.name} - {self.question_text[:30]}..."

class Badge(models.Model):
    badge_id = models.CharField(max_length=50, unique=True, primary_key=True) # e.g., "first_quiz"
    name = models.CharField(max_length=100)
    description = models.TextField()
    points = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class UserBadge(models.Model):
    profile = models.ForeignKey(QuizProfile, on_delete=models.CASCADE, related_name='badges')
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE)
    awarded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('profile', 'badge')

    def __str__(self):
        return f"{self.profile.user.username} earned {self.badge.name}"

class QuizSession(models.Model):
    profile = models.ForeignKey(QuizProfile, on_delete=models.CASCADE, related_name='sessions')
    difficulty = models.ForeignKey(Difficulty, on_delete=models.SET_NULL, null=True)
    questions = models.ManyToManyField(Question, related_name='sessions')
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True, blank=True)
    is_finished = models.BooleanField(default=False)
    score = models.IntegerField(default=0)

    def __str__(self):
        return f"Session for {self.profile.user.username} at {self.start_time}"

class SessionAnswer(models.Model):
    session = models.ForeignKey(QuizSession, on_delete=models.CASCADE, related_name='answers')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user_answer = models.CharField(max_length=10)
    is_correct = models.BooleanField()
    answered_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Answer for Q{self.question.id} in Session {self.session.id}"


class GeneratedQuiz(models.Model):
    """
    Stores quizzes generated by the LLM (e.g., from code generation).
    Persisting the raw question payload allows later review or reuse.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='generated_quizzes')
    source = models.CharField(max_length=50, default='code_generation')
    questions = models.JSONField()
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user.username} - {self.source} ({self.created_at.isoformat()})"
